import { app, BrowserWindow, ipcMain, dialog, Menu } from 'electron';
import fs from 'fs';
import path from 'path'; // You might need this later for file paths!

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

ipcMain.handle('dialog:openFile', async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    properties: ['openFile'],
    filters: [
      { name: 'Supported Files', extensions: ['csv', 'json']},
      { name: 'CSV Files', extensions: ['csv'] },
      { name: 'Project Files', extensions: ['json']}
    ]
  });

  if (!canceled) {
    const filePath = filePaths[0];
    const content = fs.readFileSync(filePath, 'utf-8');
    // We must return an object with 'content' for React to see it
    return { filePath, content }; 
  }
  return null; 
});

//for generic json data, can repurpose later
ipcMain.handle('dialog:saveFile', async (event, content) => {
  const { filePath } = await dialog.showSaveDialog({
    defaultPath: 'data.json',
    filters: [{ name: 'JSON Data', extensions: ['json'] }]
  });

  if (filePath) {
    fs.writeFileSync(filePath, content, 'utf-8');
    return true;
  }
  return false;
});

// For the Internal Project State
ipcMain.handle('dialog:saveProject', async (event, content) => {
  const { filePath } = await dialog.showSaveDialog({
    title: 'Save Project',
    defaultPath: 'schedule_project.json',
    filters: [{ name: 'Project Files', extensions: ['json'] }]
  });

  if (filePath) {
    fs.writeFileSync(filePath, content, 'utf-8');
    return filePath; // Returning the path is helpful for the UI
  }
  return null;
});

// For the Functional CSV Export
ipcMain.handle('dialog:exportCSV', async (event, content) => {
  const { filePath } = await dialog.showSaveDialog({
    title: 'Export CSV',
    defaultPath: 'processed_schedule.csv',
    filters: [{ name: 'CSV Files', extensions: ['csv'] }]
  });

  if (filePath) {
    fs.writeFileSync(filePath, content, 'utf-8');
    return filePath;
  }
  return null;
});

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

// --- START MENU DEFINITION ---
const isMac = process.platform === 'darwin';

const template: any[] = [
  ...(isMac ? [{ role: 'appMenu' }] : []), // This puts the standard Mac menu first
  {
    label: 'File',
    submenu: [
      { label: 'Import File...', accelerator: 'CmdOrCtrl+O', click: () => mainWindow.webContents.send('menu:open-file') },
      { label: 'Save Project As...', accelerator: 'CmdOrCtrl+S', click: () => mainWindow.webContents.send('menu:save-project') },
      { label: 'Export CSV...', click: () => mainWindow.webContents.send('menu:export-csv') },
      { type: 'separator' },
      { role: 'quit' }
    ]
  },
  {
    label: 'Edit',
    submenu:[
      { label: 'Hi there, you found me.' },
      { label: 'Project Preferences' },
    ]
  },
  {
    label: 'Schedule',
    submenu:[
      { label: 'Future scheduling options will go here.'},
      { label: 'Switch to Baseline (Hotkey)'},
      { label: 'Update Baseline'}
    ]
  },
  {
    label: 'Histogram',
    submenu: [
      { label: 'Set Week Ending Day' ,
      submenu: [
        { label: 'Sunday', type: 'radio', click: () => mainWindow.webContents.send('menu:set-week-end', 0) },
        { label: 'Monday', type: 'radio', click: () => mainWindow.webContents.send('menu:set-week-end', 1) },
        { label: 'Tuesday', type: 'radio', click: () => mainWindow.webContents.send('menu:set-week-end', 2) },
        { label: 'Wednesday', type: 'radio', click: () => mainWindow.webContents.send('menu:set-week-end', 3) },
        { label: 'Thursday', type: 'radio', click: () => mainWindow.webContents.send('menu:set-week-end', 4) },
        { label: 'Friday', type: 'radio', checked: true, click: () => mainWindow.webContents.send('menu:set-week-end', 5) },
        { label: 'Saturday', type: 'radio', click: () => mainWindow.webContents.send('menu:set-week-end', 6) }
      ]},
      { label: 'Preferences...' ,
        click: () => openPreferences(mainWindow)
      }
    ]
  },
  {
    label: 'View',
    submenu: [
      { role: 'reload' },
      { role: 'toggleDevTools' }
    ]
  }
];

const menu = Menu.buildFromTemplate(template);
Menu.setApplicationMenu(menu);
// --- END MENU DEFINITION ---

  // load the index.html of the app and open devtools
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.webContents.openDevTools();
};

let prefsWindow: BrowserWindow | null = null;

export const openPreferences = (mainWindow: BrowserWindow) => {
  if (prefsWindow) {
    prefsWindow.focus();
    return;
  }

  prefsWindow = new BrowserWindow({
    width: 400,
    height: 350,
    resizable: false,
    parent: mainWindow,
    modal: true, // This locks the main window until settings are closed
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // We use a hash route so React knows what to show
  prefsWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}#/preferences`);

  prefsWindow.on('closed', () => {
    prefsWindow = null;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
